# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작
    - 뒤에서부터 -1로 시작
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - **여러개의 원소를 한번에 조회**할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

In [ ]:
(5,) [2]
(4,2) [2,1]
(4,5,6) [2,2,1]
(3,3,4,5) [2,2,2,1]

In [4]:
lst = [
    [1,2,3],
    [4,5,6]
]
print(lst[0][0], lst[1][2])

1 6


In [6]:
import numpy as np

In [7]:
a = np.array(lst)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a[0,0]  

1

In [12]:
b = np.arange(12).reshape(2,2,3)
print(b.shape)
b


(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [15]:
print(b[0][0][0], b[0,0,0])
print(b[1, 0, 1])

0 0
7


In [16]:
b[1,0]

array([6, 7, 8])

In [17]:
b[0, 1]

array([3, 4, 5])

In [18]:
b[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
arr = np.arange(10)
arr #1차원

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[[0,2]]  

array([0, 2])

In [23]:
arr[[0,5,7]]

array([0, 5, 7])

In [24]:
arr2 = np.arange(12).reshape(3,4) #2차원
arr2.shape

(3, 4)

In [25]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr2[0, 1]

1

In [29]:
arr2[2, 3]

11

In [31]:
# 1,6
# arr2[0축  , 1축]
arr2[[0,2] , [1,3]]

array([ 1, 11])

In [32]:
arr2[[1, 2, 0] , [0, 1, 3]]

array([4, 9, 3])

In [35]:
arr2[1,0], arr2[2,1], arr2[0,3]

(4, 9, 3)

In [39]:
arr[1] = 100 #값 변경(대입)
arr

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
arr[2], arr[4] = 200,400 #튜플대입
arr

array([  0, 100, 200,   3, 400,   5,   6,   7,   8,   9])

In [43]:
arr[[5, 7]] = 500, 700
arr

array([  0, 100, 200,   3, 400, 500,   6, 700,   8,   9])

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [44]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
arr[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[50:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [50]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
arr[5:61:2]

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])

In [52]:
arr[::10]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
arr[50:20:-1]  #step 음수: 리버스(뒤집기), start > stop

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [56]:
arr[::-1] #전체적으로 reverse 할때는 start, stop 생략

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [60]:
arr[-1]

99

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
arr[-1:50:-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

In [68]:
a = np.arange(30).reshape(6,5)
print(a.shape)
print(a)

(6, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [72]:
a[1:5, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [73]:
a[1:5, :]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
a[1:5] # 마지막 축은 다 가져오는 경우 생략 가능

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
a[:, 1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [76]:
a[, 1:3] # 앞쪽 축은 생략할 수 없다.

SyntaxError: invalid syntax (<ipython-input-76-d5285043fb33>, line 1)

In [77]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [79]:
a[:,[1,2]]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [81]:
a[:, ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [82]:
a[::-1,:]

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [83]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [86]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [87]:
np.flip(a, axis=0)

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [88]:
np.flip(a, axis=1)

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

In [89]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [92]:
b = a[:, 1:4]
print(b.shape)
b

(6, 3)


array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [93]:
b[0,0] = 10000
b

array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [94]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

In [95]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

In [98]:
b = a[:, 1:4]
b = b.copy()
b

# b = a[:, 1:4].copy()

array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [99]:
b[0,0] = 5000
b

array([[5000,    2,    3],
       [   6,    7,    8],
       [  11,   12,   13],
       [  16,   17,   18],
       [  21,   22,   23],
       [  26,   27,   28]])

In [100]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

## boolean indexing
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [4]:
b = np.array([True, True, False, False, False])
b.shape

(5,)

In [5]:
a[b]

array([1, 2])

In [7]:
a

array([1, 2, 3, 4, 5])

In [10]:
a[[False, True, False, True, False]]

array([2, 4])

In [8]:
a[[1,3]]

array([2, 4])

In [11]:
# 벡터화 (연산)
# 배열 + 배열 : 같은 인덱스의 원소끼리 연산
# 배열 + scalar : 배열의 모든 원소들과 scalar를 연산
a = np.array([1,2,3])
b = np.array([10,20,30])
a + b

array([11, 22, 33])

In [13]:
a + 20

array([21, 22, 23])

In [15]:
a > 2

array([False, False,  True])

In [2]:
import numpy as np
arr = np.arange(100)
np.random.shuffle(arr)
arr

array([86,  1, 49, 25, 87, 82, 27,  9, 85, 78, 23, 39, 46, 41, 26, 32, 58,
       17,  3, 61, 95, 89, 21, 72, 75, 93, 55, 13, 96, 31, 57, 99, 77, 80,
       84, 70, 98, 74, 92, 12, 22, 64, 47, 19, 79, 88, 36, 43, 33, 37, 54,
       68, 65, 91, 63, 40, 69, 16, 51, 35, 44, 20, 45, 62, 18, 66, 76, 71,
       11, 34, 60, 90, 73, 83, 14, 53, 81,  0, 56, 24, 30, 67,  2, 94,  5,
        8, 42,  4, 15,  7, 10, 97, 50,  6, 48, 28, 52, 38, 29, 59])

In [20]:
# arr의 원소중에서 50이상인 값들만 조회
arr[arr >= 50]

array([74, 86, 80, 77, 68, 92, 52, 70, 96, 93, 88, 73, 51, 90, 63, 97, 58,
       54, 71, 69, 65, 76, 95, 67, 62, 87, 55, 94, 99, 98, 50, 78, 81, 91,
       89, 82, 83, 79, 66, 85, 57, 53, 56, 59, 64, 72, 60, 61, 84, 75])

In [21]:
arr2 = np.arange(100).reshape(2,50)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [24]:
arr2[arr2 >= 30]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
       81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
       98, 99])

In [36]:
# 20 ~ 30
arr[(arr >= 20) & (arr <= 30)]

array([24, 20, 27, 21, 25, 30, 26, 22, 28, 29, 23])

In [39]:
# 50보다 크지 않은 값들
arr[~(arr > 50)]

array([38,  5, 24, 12, 20, 27,  4, 16, 13,  9, 33, 37, 21, 25, 19, 30, 46,
       26, 22, 15, 31, 28, 34,  0, 47,  8, 35, 43, 14, 32,  6, 18, 50, 29,
       10, 40, 48,  1, 11, 45, 17,  2,  3, 36, 42, 39, 44, 23,  7, 49, 41])

## 넘파이에서 비교연산자
- 파이썬 비교 연산자인 and, or, not을 사용못함.
- `&` : and
- `|` : or
- `~` : not
- 피연산자들은 ( )로 묶어야 한다.

### np.where()
- np.where(boolean 배열) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(booean 배열, True를 대체할 값, False를 대체할 값)
    - True와 False를 다른 값으로 변경한다.

In [42]:
a = np.array([True, False, True])
r=np.where(a) #True인 indexe들을 튜플안에 ndarray에 담아서 반환
print(type(r))
print(r[0])

<class 'tuple'>
[0 2]


In [9]:
#arr에서 50 이상인 값들의 index를 조회
np.where(arr >= 99)

(array([31], dtype=int64),)

In [50]:
np.where(a, '참', '거짓') #True는 참, False 거짓 으로 변경한 ndarray 객체 반화

array(['참', '거짓', '참'], dtype='<U2')

In [52]:
np.where(arr >= 50, "50이상", "50미만")

array(['50미만', '50이상', '50이상', '50미만', '50미만', '50미만', '50미만', '50미만',
       '50이상', '50이상', '50이상', '50이상', '50미만', '50이상', '50미만', '50미만',
       '50미만', '50미만', '50이상', '50미만', '50미만', '50미만', '50이상', '50미만',
       '50미만', '50이상', '50이상', '50이상', '50이상', '50미만', '50이상', '50이상',
       '50미만', '50이상', '50이상', '50이상', '50이상', '50미만', '50미만', '50이상',
       '50이상', '50미만', '50이상', '50이상', '50미만', '50이상', '50미만', '50미만',
       '50미만', '50미만', '50미만', '50이상', '50미만', '50미만', '50미만', '50이상',
       '50이상', '50이상', '50미만', '50미만', '50이상', '50이상', '50이상', '50이상',
       '50이상', '50미만', '50미만', '50미만', '50이상', '50이상', '50이상', '50미만',
       '50미만', '50미만', '50미만', '50이상', '50이상', '50이상', '50미만', '50이상',
       '50미만', '50이상', '50이상', '50미만', '50미만', '50미만', '50미만', '50미만',
       '50이상', '50이상', '50이상', '50이상', '50미만', '50이상', '50이상', '50이상',
       '50이상', '50미만', '50미만', '50미만'], dtype='<U4')

In [53]:
# 50이상인 값은 "50이상"으로 변경하고 50미만인 값은 그대로 나오도록
np.where(arr>=50, "50이상", arr)

array(['38', '50이상', '50이상', '5', '24', '12', '20', '27', '50이상', '50이상',
       '50이상', '50이상', '4', '50이상', '16', '13', '9', '33', '50이상', '37',
       '21', '25', '50이상', '19', '30', '50이상', '50이상', '50이상', '50이상',
       '46', '50이상', '50이상', '26', '50이상', '50이상', '50이상', '50이상', '22',
       '15', '50이상', '50이상', '31', '50이상', '50이상', '28', '50이상', '34',
       '0', '47', '8', '35', '50이상', '43', '14', '32', '50이상', '50이상',
       '50이상', '6', '18', '50이상', '50이상', '50이상', '50이상', '50이상', '29',
       '10', '40', '50이상', '50이상', '50이상', '48', '1', '11', '45', '50이상',
       '50이상', '50이상', '17', '50이상', '2', '50이상', '50이상', '3', '36', '42',
       '39', '44', '50이상', '50이상', '50이상', '50이상', '23', '50이상', '50이상',
       '50이상', '50이상', '7', '49', '41'], dtype='<U11')

In [54]:
# 0: 여성, 1: 남성
gender = np.random.choice([0,1], size= 20)
gender

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0])

In [57]:
np.where(gender==0, "여성", "남성")

array(['여성', '남성', '남성', '여성', '남성', '여성', '여성', '여성', '여성', '남성', '여성',
       '남성', '남성', '남성', '남성', '남성', '여성', '남성', '남성', '여성'], dtype='<U2')

- 2차원도 마찮가지
    - 단 where는 축별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

In [4]:
arr2 = [
    [1,10,7],
    [4,2,10],
    [10,2,8]
]
arr2 = np.array(arr2)

In [10]:
r = np.where(arr2>=10)
print(type(r))
r

# (0,1), (0,2), (1, 2), (2,0), (2,2)

<class 'tuple'>


(array([0, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

In [64]:
np.where(arr2>=5, '크다', '작다')

array([['작다', '크다', '크다'],
       ['작다', '작다', '크다'],
       ['크다', '작다', '크다']], dtype='<U2')

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [65]:
np.any([False, False, False])

False

In [66]:
np.any([True, False, False])

True

In [67]:
np.all([True, True, True])

True

In [68]:
np.all([True, False, True])

False

In [71]:
np.any(arr > 50) #arr안에 50 초과인 값이 하나라도 있는지?

True

In [72]:
np.all(arr > 50) #arr의 모든값이 50 초과인지?

False

In [76]:
# 50초과인 값이 몇개?
np.sum(arr > 50)
# sum(): 배열내 원소의 총합계. boolean배열->True:1, False:0 으로 처리후 계산.


6

In [75]:
arr > 50

array([False,  True,  True, False, False, False, False, False,  True,
        True,  True,  True, False,  True, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True, False,
        True, False, False, False, False, False,  True, False, False,
       False,  True,  True,  True, False, False,  True,  True, False,
        True,  True, False, False, False,  True,  True,  True, False,
       False, False, False,  True,  True,  True, False,  True, False,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False, False,
       False])

### 정렬
- np.sort(arr)/ndarray.sort(): arr을 정렬
    - np.sort(배열): 배열을 정렬한 결과를 가진 새로운 배열을 반환(카피본). 원본은 안바뀜
    - 배열.sort() : 원본 배열을 정렬.
- np.argsort(arr): 정렬 후 index를 반환
- 오름차순정렬만 지원. 내림차순을 할 경우 정렬후 reverse 해야 한다.

In [78]:
x = np.sort(arr)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [79]:
arr

array([38, 74, 86,  5, 24, 12, 20, 27, 80, 77, 68, 92,  4, 52, 16, 13,  9,
       33, 70, 37, 21, 25, 96, 19, 30, 93, 88, 73, 51, 46, 90, 63, 26, 97,
       58, 54, 71, 22, 15, 69, 65, 31, 76, 95, 28, 67, 34,  0, 47,  8, 35,
       62, 43, 14, 32, 87, 55, 94,  6, 18, 99, 98, 50, 78, 81, 29, 10, 40,
       91, 89, 82, 48,  1, 11, 45, 83, 79, 66, 17, 85,  2, 57, 53,  3, 36,
       42, 39, 44, 56, 59, 64, 72, 23, 60, 61, 84, 75,  7, 49, 41])

In [81]:
y = arr.sort()
print(y)

None


In [83]:
arr

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [84]:
# 내림차순 정렬
a = np.array([3,1,5,2])
a

array([3, 1, 5, 2])

In [88]:
np.sort(a)[::-1]

array([5, 3, 2, 1])

In [89]:
a

array([3, 1, 5, 2])

In [90]:
np.argsort(a) #index

array([1, 3, 0, 2], dtype=int64)

In [91]:
np.sort(a)

array([1, 2, 3, 5])

In [92]:
# 내림차순
np.argsort(a)[::-1]

array([2, 0, 3, 1], dtype=int64)

In [93]:
a[np.argsort(a)]

array([1, 2, 3, 5])

In [95]:
l = [
    [3,1,5],
    [1,2,9],
    [10,20,5]
]
b = np.array(l)
b

array([[ 3,  1,  5],
       [ 1,  2,  9],
       [10, 20,  5]])

In [96]:
np.sort(b)  #다차원 배열 정렬에서 axis를 생략하면 마지막 축을 기준으로 정렬.

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])

In [97]:
np.sort(b, axis=0) #0축 기준으로 정렬

array([[ 1,  1,  5],
       [ 3,  2,  5],
       [10, 20,  9]])

In [98]:
np.sort(b, axis=1) # 1축 기준으로 정렬. 

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])