In [ ]:
파일명 : 이름.ipynb
이메일: kgmyh@naver.com

1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.

In [1]:
import numpy as np
a = np.array([10,7,5,90,100])
print(a)

[ 10   7   5  90 100]


In [ ]:
2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.

In [5]:
b = np.arange(100,201,2)
b

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [2]:
np.linspace(100,200,num=51)

array([100., 102., 104., 106., 108., 110., 112., 114., 116., 118., 120.,
       122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
       144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164.,
       166., 168., 170., 172., 174., 176., 178., 180., 182., 184., 186.,
       188., 190., 192., 194., 196., 198., 200.])

In [ ]:
3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.

In [13]:
c = np.zeros_like(b)
c.shape
c1 = np.zeros(shape=b.shape)
c1.shape

(51,)

In [ ]:
4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)

In [18]:
d = np.arange(1100,10001,100).reshape(2,5,-1)
print(d.shape)
print(d)

(2, 5, 9)
[[[ 1100  1200  1300  1400  1500  1600  1700  1800  1900]
  [ 2000  2100  2200  2300  2400  2500  2600  2700  2800]
  [ 2900  3000  3100  3200  3300  3400  3500  3600  3700]
  [ 3800  3900  4000  4100  4200  4300  4400  4500  4600]
  [ 4700  4800  4900  5000  5100  5200  5300  5400  5500]]

 [[ 5600  5700  5800  5900  6000  6100  6200  6300  6400]
  [ 6500  6600  6700  6800  6900  7000  7100  7200  7300]
  [ 7400  7500  7600  7700  7800  7900  8000  8100  8200]
  [ 8300  8400  8500  8600  8700  8800  8900  9000  9100]
  [ 9200  9300  9400  9500  9600  9700  9800  9900 10000]]]


In [ ]:
5. (4,4) 형태의 단위행렬(항등행렬)을 생성.

In [19]:
i = np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
i1 = np.eye(4,4)
i1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
20, 90, 80, 100, -20, 30
50, -10, 25, 120, -40, 90

In [19]:
a = np.array([[20, 90, 80, 100, -20, 30],[50, -10, 25, 120, -40, 90]])
a.ndim, a.shape, a.size

(2, (2, 6), 12)

In [ ]:
7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성.

In [37]:
np.random.normal(10,1,size=(3,2,7))
np.random.normal(size=(3,2,7))

array([[[ 0.92472154, -0.71936844,  0.01621008, -0.00797315,
         -0.97641272, -0.04454114, -0.62931467],
        [-0.53289285,  0.44720249,  0.39156479, -0.2955071 ,
          0.54471869,  0.09701055, -0.3026811 ]],

       [[-0.4569284 , -0.05137892, -1.42040231, -0.05402574,
         -1.49835382, -0.86590013,  2.53867404],
        [ 0.32592189,  0.74170248, -0.01390945, -0.32279086,
         -0.89009637, -0.0801198 , -0.5763459 ]],

       [[ 0.28425412, -0.68414977,  1.00195404,  0.81267303,
          0.7101515 , -1.38108815,  1.04528492],
        [-1.21013087,  1.23275924,  0.2443867 ,  1.11606492,
         -0.22767393, -0.0852714 , -1.88310466]]])

In [ ]:
8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.

In [40]:
a = np.random.randint(1,100,(4,5),dtype=int)
print(a)
np.save('arr.npy', a)

[[64 35 13 13 82]
 [24 51 83 46 85]
 [37  7  2 30 82]
 [38 30 71 47 11]]


In [41]:
import os
#배열 저장 디렉토리: backup
backup_dir = 'backup'
if not os.path.isdir(backup_dir): # 현재 경로에 backup이란 디렉토리가 없냐? 없으면 디렉토리 생성.
    os.mkdir(backup_dir)
np.save('backup/arr.npy', a)

In [ ]:
9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.

In [42]:
print(np.load('arr.npy'))
a9 = np.load('backup/arr.npy')
print(a9)

[[64 35 13 13 82]
 [24 51 83 46 85]
 [37  7  2 30 82]
 [38 30 71 47 11]]
[[64 35 13 13 82]
 [24 51 83 46 85]
 [37  7  2 30 82]
 [38 30 71 47 11]]


In [43]:
a9

array([[64, 35, 13, 13, 82],
       [24, 51, 83, 46, 85],
       [37,  7,  2, 30, 82],
       [38, 30, 71, 47, 11]])

In [ ]:
10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.

In [44]:
arr = np.load('arr.npy')
total = np.add.reduce(arr, axis=None)
print(total)
axis0 = np.add.reduce(arr, axis=0)
print(axis0)
axis1 = np.add.reduce(arr,axis=1)
print(axis1)

851
[163 123 169 136 260]
[207 289 158 197]


In [48]:
arr = np.load('arr.npy')
am = np.sum(arr,axis=1)
print(am)

[207 289 158 197]


In [ ]:
11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.

In [55]:
a = np.random.choice([True,False],(5,10))
values, counts = np.unique(a, return_counts=True)
print(a)
print(values[1])
print(counts[1])
print(np.sum(a))

[[False False False False False  True  True  True  True False]
 [ True False  True  True  True  True  True False  True  True]
 [False False False  True  True False False  True  True False]
 [ True  True  True  True False False False  True False  True]
 [False False False  True False False False  True False  True]]
True
25
25


In [50]:
a = np.random.choice([True,False],(5,10),p=[0.9,0.1])
np.sum(a)

45

In [54]:
a3 = np.random.randint(0,2,size=(5,10),dtype=bool)
print(a3)

[[False  True False  True False False False  True False  True]
 [False False False  True False  True  True  True False  True]
 [False False  True False False  True  True  True  True False]
 [ True  True False False False False False False  True  True]
 [ True  True False  True  True False  True False False  True]]


In [ ]:
12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
 0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.

In [56]:
a = np.random.randint(0,29,size=(5,6))
a

array([[ 0, 24,  3, 25, 25,  4],
       [26, 20, 27,  3,  7,  8],
       [24, 21, 26, 13,  0, 18],
       [19, 25, 23,  5, 17,  9],
       [ 6, 16, 11, 14, 16, 11]])

In [ ]:
12. index (1,1), (2,3), (1,5)의 값들 조회

In [57]:
a[1,1], a[2,3], a[1,5]

(20, 13, 8)

In [58]:
#fancy indexing
a[[1,2,1],[1,3,5]]

array([20, 13,  8])

In [ ]:
13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.

In [72]:
a[1:4,1:4]

array([[20, 27,  3],
       [21, 26, 13],
       [25, 23,  5]])

In [ ]:
14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회.

In [77]:
print(np.flip(a[1:4,1:4]))
print(np.flip(a[1:4,1:4],axis=1)) # axis 1만 reversing
print(np.flip(a[1:4,1:4],axis=0)) # axis 0만 reversing

[[ 5 23 25]
 [13 26 21]
 [ 3 27 20]]
[[ 3 27 20]
 [13 26 21]
 [ 5 23 25]]
[[25 23  5]
 [21 26 13]
 [20 27  3]]


In [78]:
#[start:stop:-step] start>stop
print(a[3:0:-1,3:0:-1])
print(a[1:4,3:0:-1]) # axis 1만 reversing
print(a[3:0:-1,1:4]) # axis 0만 reversing


[[ 5 23 25]
 [13 26 21]
 [ 3 27 20]]
[[ 3 27 20]
 [13 26 21]
 [ 5 23 25]]
[[25 23  5]
 [21 26 13]
 [20 27  3]]


In [ ]:
15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.

In [80]:
print(a[a>=15])
print(np.mean(a[a>=15]))


[27 25 16 28 19 23 17 18 20 19]
21.2


In [ ]:
16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
    ex: (0,0), (0,1) 식으로 출력

In [86]:
indices = np.where(a>=15)
print(type(indices))
for idx in zip(indices[0],indices[1]):
    #print(idx)
    print(idx,end=',')
# enumerate(자료구조), zip(자료구조1, 자료구조2, [,.....]), range()

<class 'tuple'>
(0, 1),(0, 3),(0, 4),(1, 0),(1, 1),(1, 2),(2, 0),(2, 1),(2, 2),(2, 5),(3, 0),(3, 1),(3, 2),(3, 4),(4, 1),(4, 4),

In [81]:
np.where(a>= 15)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4], dtype=int64),
 array([1, 3, 4, 0, 1, 2, 0, 1, 2, 5, 0, 1, 2, 4, 1, 4], dtype=int64))

In [82]:
print(np.where(a>=15))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4], dtype=int64), array([1, 3, 4, 0, 1, 2, 0, 1, 2, 5, 0, 1, 2, 4, 1, 4], dtype=int64))


In [ ]:
17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
결과
[[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]   

In [89]:
a = [[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]
np.sort(a, 1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [90]:
np.sort(a,axis=1)[:,::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24]])

In [92]:
x = np.random.permutation(a)
x[:,::-1]

array([[ 0,  1,  2,  3,  4,  5],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
(3, 2) shape의 배열을 생성 하시오. 

In [107]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.

In [96]:
r1 = a[np.newaxis,:,:]
r1.shape

(1, 3, 2)

In [100]:
r3 = a[np.newaxis,...]
r3.shape

(1, 3, 2)

In [97]:
b  = a.reshape(1,3,2)
b.shape

(1, 3, 2)

In [98]:
r2 = np.expand_dims(a,axis=0)
r2.shape

(1, 3, 2)

In [ ]:
19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.

In [99]:
c1 = a[np.newaxis,...,np.newaxis]
c1.shape

(1, 3, 2, 1)

In [101]:
c = a.reshape(1,3,2,1)
c.shape

(1, 3, 2, 1)

In [ ]:
20. 배열을 1차원 배열로 변환한 배열을 생성.

In [103]:
d1 = a.flatten()
d1, d1.shape

(array([0, 1, 2, 3, 4, 5]), (6,))

In [104]:
d = a.reshape(6)
d, d.shape

(array([0, 1, 2, 3, 4, 5]), (6,))

In [ ]:
21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))

In [109]:
r = np.append(a,[[60,70],[80,90],[100,110]], axis=1)
r, r.shape

(array([[  0,   1,  60,  70],
        [  2,   3,  80,  90],
        [  4,   5, 100, 110]]),
 (3, 4))

In [113]:
a1 = np.append(a, [[4,4],[5,5]], axis=0)
a1, a1.shape

(array([[0, 1],
        [2, 3],
        [4, 5],
        [4, 4],
        [5, 5]]),
 (5, 2))

In [ ]:
22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.
[
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
]

In [115]:
score = np.array([
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
])

In [ ]:
22. 각 과목별 평균점수를 조회.

In [116]:
avg = np.mean(score, axis = 0)
avg

array([66., 70., 70., 78.])

In [ ]:
23. 각 과목별 평균 점수를 성적 배열에 추가. 

In [117]:
np.append(score, [avg], axis = 0)

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

In [126]:
score1 = np.insert(score, 0, avg, axis=0)
score1

array([[ 66,  70,  70,  78],
       [ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [ ]:
24. 각 학생들의 평균 점수 조회

In [126]:
mean = np.mean(score, axis=1)
mean

array([75. , 85. , 67.5, 57.5, 70. ])

In [123]:
np.mean(score, axis=1, keepdims=True)

array([[75. ],
       [85. ],
       [67.5],
       [57.5],
       [70. ]])

In [ ]:
25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회

In [136]:
np.argmax(score, axis=0) + 1

array([3, 1, 2, 1], dtype=int64)

In [ ]:
26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.

In [130]:
subject = np.array(['국어','영어','수학','과학'])

In [134]:
subject[np.argmin(score, axis=1)]

array(['국어', '국어', '과학', '국어', '영어'], dtype='<U2')

In [137]:
np.argmin(score, axis=1)

array([0, 0, 3, 0, 1], dtype=int64)

In [ ]:
27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회

In [139]:
print(np.std(score, axis= 0))
print("편차작은과목: ", subject[np.argmin(np.std(score, axis= 0))])
print("편차큰과목: ", subject[np.argmax(np.std(score, axis= 0))])

[17.43559577 12.64911064 10.95445115 23.15167381]
편차작은과목:  수학
편차큰과목:  과학


In [ ]:
28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회

In [140]:
print(np.std(score, axis= 1))
print("편차작은학생: ", np.argmin(np.std(score, axis= 1))+1)
print("편차큰학생: ", np.argmax(np.std(score, axis= 1))+1)

[16.58312395  5.         14.79019946 14.79019946 18.70828693]
편차작은학생:  2
편차큰학생:  5


In [ ]:
29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.
A:
[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]
B:
[
  [10,20,30],
  [40,50,60],
  [70,80,90]
]

In [141]:
a = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])
b = np.array([
  [10,20,30],
  [40,50,60],
  [70,80,90]
]
)

In [ ]:
29. 두 배열을 수직방향으로 합치기. 

In [142]:
a.shape, b.shape

((3, 3), (3, 3))

In [145]:
k = np.concatenate([a,b],axis=0)
k, k.shape

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]),
 (6, 3))

In [146]:
c = np.vstack([a,b])
print(c, c.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]] (6, 3)


In [ ]:
30. 29에서 합친 배열을 수평방향으로 index 2를 기준으로 나누기.

In [148]:
np.split(c,[2],axis=1)

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 20],
        [40, 50],
        [70, 80]]),
 array([[ 3],
        [ 6],
        [ 9],
        [30],
        [60],
        [90]])]

In [152]:
np.hsplit(c,[2])  #vsplit(), hsplit() : 2차원(행렬)

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 20],
        [40, 50],
        [70, 80]]),
 array([[ 3],
        [ 6],
        [ 9],
        [30],
        [60],
        [90]])]

In [149]:
np.split(c,[2],axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [155]:
np.vsplit(c,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [ ]:
31-32 다움은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
[10, 50, 75, 20, 70, 50, 80]

In [158]:
import numpy as np
score = np.array([10, 50, 75, 20, 70, 50, 80])


In [ ]:
31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회

In [167]:
mean = np.mean(score)
a2 = score[score>=mean]
print(mean)
print(a2)
print(a2.size)
a = np.sum(score>=mean)
a

50.714285714285715
[75 70 80]
3


3

In [ ]:
32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.

In [170]:
np.mean(score>=mean)*100

42.857142857142854

In [171]:
np.sum(score>=mean)/score.size*100

42.857142857142854

In [ ]:
33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
[7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000]
 

In [173]:
import numpy as np
salary = np.array([7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420, 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120, 7100, 5220, 8810, 253000])

In [ ]:
33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.

In [174]:
np.quantile(salary, q=0.75) #,interpolation='lower')

8335.0

In [ ]:
34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.

In [175]:
np.quantile(salary, q=0.25)#, interpolation='higher')

5080.0

In [176]:
# 4분위수: 0.25,0.5,0.75
np.quantile(salary, q=[0.25,0.5,0.75])

array([5080., 7455., 8335.])

In [177]:
np.percentile(salary, q=[25,50,75])

array([5080., 7455., 8335.])

In [ ]:
35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.

In [178]:
# 표준편차가 크고 최소값과 최대값의 차이가 커서, 평균을 왜곡할 가능성이 있으므로, 평균값보다는 중앙값을 대푯값으로 사용하는 것이 맞다.
std = np.std(salary) # 표준편차
max = np.nanmax(salary) # 최댓값
min = np.nanmin(salary) # 최솟값
med = np.median(salary) # 중간값
mean = np.mean(salary) # 평균
print(std, min, max)
print(med, mean)

53793.63669617439 1420 253000
7455.0 18739.0


In [11]:
avg = np.mean(salary)
print(avg)

18739.0


53793.63669617439

In [13]:
np.var(salary)

2893755349.0

In [ ]:
np.