In [ ]:
파일명 : 이름.ipynb
이메일: kgmyh@naver.com

1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.

In [3]:
import numpy as np
a = np.array([10,7,5,90,100])
print(a)

[ 10   7   5  90 100]


In [ ]:
2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.

In [6]:
b = np.arange(100,201,2)
b

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [ ]:
3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.

In [7]:
c = np.zeros(100)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)

In [8]:
d = np.arange(1100,10001,100).reshape(2,5,-1)
d

array([[[ 1100,  1200,  1300,  1400,  1500,  1600,  1700,  1800,  1900],
        [ 2000,  2100,  2200,  2300,  2400,  2500,  2600,  2700,  2800],
        [ 2900,  3000,  3100,  3200,  3300,  3400,  3500,  3600,  3700],
        [ 3800,  3900,  4000,  4100,  4200,  4300,  4400,  4500,  4600],
        [ 4700,  4800,  4900,  5000,  5100,  5200,  5300,  5400,  5500]],

       [[ 5600,  5700,  5800,  5900,  6000,  6100,  6200,  6300,  6400],
        [ 6500,  6600,  6700,  6800,  6900,  7000,  7100,  7200,  7300],
        [ 7400,  7500,  7600,  7700,  7800,  7900,  8000,  8100,  8200],
        [ 8300,  8400,  8500,  8600,  8700,  8800,  8900,  9000,  9100],
        [ 9200,  9300,  9400,  9500,  9600,  9700,  9800,  9900, 10000]]])

In [ ]:
5. (4,4) 형태의 단위행렬(항등행렬)을 생성.

In [9]:
e = np.arange(16).reshape(4,4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
20, 90, 80, 100, -20, 30
50, -10, 25, 120, -40, 90

In [19]:
a = np.array([[20, 90, 80, 100, -20, 30],[50, -10, 25, 120, -40, 90]])
a.ndim, a.shape, a.size

(2, (2, 6), 12)

In [ ]:
7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성.

In [20]:
np.random.normal(10,1,(3,2,5))

array([[[10.0932203 ,  9.74166307,  8.69561857,  8.93436111,
         10.24712018],
        [ 9.73578888,  9.85805023, 10.37177577, 10.62495425,
          9.89712865]],

       [[ 9.37891194, 11.58845943,  9.57015751, 10.84806915,
          9.14305592],
        [10.59734238, 10.32731517,  9.77734572,  9.37706779,
         10.45931429]],

       [[10.89828696,  8.34699478,  8.92945166,  8.9965524 ,
          9.65791432],
        [ 8.81884417, 10.88999034,  9.13402622,  9.48648371,
          8.83312446]]])

In [ ]:
8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.

In [30]:
a = np.random.randint(1,100,(4,5),dtype=int)
print(a)
np.save('arr.npy', a)

[[23 36 82  6 27]
 [39 58 24 17 12]
 [63 83 13  9 37]
 [55 68  6 34 80]]


In [ ]:
9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.

In [31]:
print(np.load('arr.npy'))

[[23 36 82  6 27]
 [39 58 24 17 12]
 [63 83 13  9 37]
 [55 68  6 34 80]]


In [ ]:
10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.

In [36]:
arr = np.load('arr.npy')
total = np.add.reduce(arr, axis=None)
print(total)
axis0 = np.add.reduce(arr, axis=0)
print(axis0)
axis1 = np.add.reduce(arr,axis=1)
print(axis1)

772
[180 245 125  66 156]
[174 150 205 243]


In [ ]:
11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.

In [56]:
a = np.random.choice([True,False],(5,10))
values, counts = np.unique(a, return_counts=True)
print(values[1])
print(counts[1])

True
23


In [ ]:
12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
 0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.

In [57]:
a = np.random.randint(0,29,(5,6))
a

array([[ 8, 27, 25,  3, 14,  3],
       [ 3,  0, 16, 28,  8, 12],
       [ 9, 19,  6,  8, 23,  0],
       [ 3, 10, 12, 17, 11, 12],
       [11, 11, 18, 20,  8, 19]])

In [ ]:
12. index (1,1), (2,3), (1,5)의 값들 조회

In [59]:
a[1,1], a[2,3], a[1,5]

(0, 8, 12)

In [ ]:
13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.

In [62]:
a[1:4,1:4]

array([[ 0, 16, 28],
       [19,  6,  8],
       [10, 12, 17]])

In [ ]:
14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회.

In [71]:
np.flip(a[1:4,1:4])

array([[17, 12, 10],
       [ 8,  6, 19],
       [28, 16,  0]])

In [ ]:
15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.

In [80]:
print(a[a>=15])
print(np.mean(a[a>=15]))


[27 25 16 28 19 23 17 18 20 19]
21.2


In [ ]:
16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
    ex: (0,0), (0,1) 식으로 출력

In [88]:
np.where(a>= 15)

(array([0, 0, 1, 1, 2, 2, 3, 4, 4, 4], dtype=int64),
 array([1, 2, 2, 3, 1, 4, 3, 2, 3, 5], dtype=int64))

In [ ]:
17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
결과
[[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]   

In [91]:
a = [[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]
np.sort(a, 1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
(3, 2) shape의 배열을 생성 하시오. 

In [102]:
a = np.arange(6).reshape(3,2)

In [ ]:
18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.

In [103]:
b  = a.reshape(1,3,2)
b

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [ ]:
19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.

In [104]:
c = a.reshape(1,3,2,1)
c

array([[[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]]]])

In [ ]:
20. 배열을 1차원 배열로 변환한 배열을 생성.

In [105]:
d = a.reshape(6)
d

array([0, 1, 2, 3, 4, 5])

In [ ]:
21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))

In [110]:
a.shape
a1 = np.append(a, [[4,4],[5,5]], axis=0)
a1.shape

(5, 2)

In [ ]:
22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.
[
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
]

In [111]:
score = np.array([
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
])

In [ ]:
22. 각 과목별 평균점수를 조회.

In [115]:
avg = np.mean(score, axis = 0)
avg

array([66., 70., 70., 78.])

In [ ]:
23. 각 과목별 평균 점수를 성적 배열에 추가. 

In [126]:
score1 = np.insert(score, 0, avg, axis=0)
score1

array([[ 66,  70,  70,  78],
       [ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [ ]:
24. 각 학생들의 평균 점수 조회

In [127]:
score1[0]

array([66, 70, 70, 78])

In [ ]:
25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회

In [132]:
np.argmax(score, axis=0)

array([2, 0, 1, 0], dtype=int64)

In [ ]:
26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.

In [133]:
np.argmin(score, axis=0)

array([3, 4, 0, 2], dtype=int64)

In [ ]:
27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회

In [146]:
print(np.std(score, axis= 0))
print("편차작은과목: ", np.argmin(np.std(score, axis= 0)))
print("편차큰과목: ", np.argmax(np.std(score, axis= 0)))

[17.43559577 12.64911064 10.95445115 23.15167381]
편차작은과목:  2
편차큰과목:  3


In [ ]:
28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회

In [145]:
print(np.std(score, axis= 1))
print("편차작은학생: ", np.argmin(np.std(score, axis= 1)))
print("편차큰학생: ", np.argmax(np.std(score, axis= 1)))

[16.58312395  5.         14.79019946 14.79019946 18.70828693]
편차작은학생:  1
편차큰학생:  4


In [ ]:
29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.
A:
[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]
B:
[
  [10,20,30],
  [40,50,60],
  [70,80,90]
]

In [16]:
a = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])
b = np.array([
  [10,20,30],
  [40,50,60],
  [70,80,90]
]
)

In [ ]:
29. 두 배열을 수직방향으로 합치기. 

In [17]:
a.shape, b.shape

((3, 3), (3, 3))

In [20]:
c = np.vstack([a,b])
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
30. 29에서 합친 배열을 수평방향으로 index 2를 기준으로 나누기.

In [21]:
np.vsplit(c,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [ ]:
31-32 다움은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
[10, 50, 75, 20, 70, 50, 80]

In [1]:
import numpy as np
score = np.array([10, 50, 75, 20, 70, 50, 80])


In [ ]:
31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회

In [151]:
a = np.sum(score>np.mean(score))
a

3

In [ ]:
32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.

In [153]:
np.sum(score>np.mean(score))/score.size

0.42857142857142855

In [ ]:
33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
[7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000]
 

In [4]:
import numpy as np
salary = np.array([7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420, 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120, 7100, 5220, 8810, 253000])

In [ ]:
33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.

In [6]:
np.quantile(salary, q=0.75, interpolation='lower')

8200

In [ ]:
34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.

In [8]:
np.quantile(salary, q=0.25, interpolation='higher')

5120

In [ ]:
35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.

In [15]:
# 표준편차가 크고 최소값과 최대값의 차이가 커서, 평균을 왜곡할 가능성이 있으므로, 평균값보다는 중앙값을 대푯값으로 사용하는 것이 맞다.
std = np.std(salary)
max = np.nanmax(salary)
min = np.nanmin(salary)
med = np.median(salary)
print(std, min, max)
print(med)

53793.63669617439 1420 253000
7455.0


In [11]:
avg = np.mean(salary)
print(avg)

18739.0


53793.63669617439

In [13]:
np.var(salary)

2893755349.0

In [ ]:
np.